

name: merge all dependabot pull requests

on: workflow_dispatch

jobs:
  get_pull_requests_ids:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.get_pull_requests.outputs.result }}
    steps:
    - id: get_pull_requests
      uses: jd1378/filter_pull_requests_by_author@v1.2.1
      with: 
        token: ${{ secrets.GITHUB_TOKEN }}
        author: app/dependabot
        state: open

  merge:
    needs: get_pull_requests_ids
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.get_pull_requests_ids.outputs.matrix)}}
    steps:
      - name: merge pr id
        run: gh pr merge --auto --merge "$PR_URL"
        env: 
          PR_URL: ${{ matrix.html_urls }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
