

name: trigger dependabot auto merge
on: 
  workflow_dispatch:
    inputs:
      comment_body:
        description: 'comment body to send on pull requests'
        required: true 
        type: string 

jobs:
  get_pull_requests_ids:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.get_pull_requests.outputs.result }}
    steps:
    - id: get_pull_requests
      uses: jd1378/filter_pull_requests_by_author@v1.0.0-beta-1
      with: 
        token: ${{ secrets.GITHUB_TOKEN }}
        author: app/dependabot
        state: open

  add_comment:
    needs: get_pull_requests_ids
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.get_pull_requests_ids.outputs.matrix)}}
    steps:
      - name: add comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          token: ${{ secrets.PAT_TOKEN || secrets.GITHUB_TOKEN }}
          issue-number: ${{ matrix.ids }}
          body: ${{ github.event.inputs.comment_body }} 
